export type Color = {
  id: number;
  name: string;
  brand: string;
  /** Little Greene: printed swatch image in /public/images/swatches */
  filename?: string;
  /** LOGGIA: flat colour value used to render the swatch tile */
  hex?: string;
  /** LOGGIA: optional room scene shown in the colour detail modal */
  scene?: string;
};

const colorFilenames = [
  "1_China Clay_Swatch_HR.jpg",
  "3_Light Peachblossom_Swatch_HR.jpg",
  "6_Ashes of Roses_Swatch_HR.jpg",
  "7_Adventurer_Swatch_HR.jpg",
  "8_Purple Brown_Swatch_HR.jpg",
  "13_Mischief_Swatch_HR.jpg",
  "14_Baked Cherry_Swatch_HR.jpg",
  "15_Bronze Red_Swatch_HR.jpg",
  "21_Orange Aurora_Swatch_HR.jpg",
  "24_Heat_Swatch_HR.jpg",
  "25_Hollyhock_Swatch_HR.jpg",
  "26_Julies Dream_Swatch_HR.jpg",
  "29_Beauvais Lilac_Swatch_HR.jpg",
  "31_Roman Plaster_Swatch_HR.jpg",
  "33_Linen Wash_Swatch_HR.jpg",
  "34_Stone-Pale-Warm_Swatch_HR.jpg",
  "37_Stock_Swatch_HR.jpg",
  "38_Hammock_Swatch_HR.jpg",
  "39_Clay_Swatch_HR.jpg",
  "40_Silt_Swatch_HR.jpg",
  "41_Whitening_Swatch_HR.jpg",
  "46_Yellow-Pink_Swatch_HR.jpg",
  "47_Mister David_Swatch_HR.jpg",
  "49_First Light_Swatch_HR.jpg",
  "53_Light Gold_Swatch_HR.jpg",
  "56_Invisible Green_Swatch_HR.jpg",
  "63_Oak Apple_Swatch_HR.jpg",
  "64_Bath Stone_Swatch_HR.jpg",
  "70_Pale Lime_Swatch_HR.jpg",
  "71_Citrine_Swatch_HR.jpg",
  "72_Olive Colour_Swatch_HR.jpg",
  "74_White Lead_Swatch_HR.jpg",
  "77_Portland Stone_Swatch_HR.jpg",
  "78_Tracery II_Swatch_HR.jpg",
  "79_Normandy Grey_Swatch_HR.jpg",
  "80_Sage Green_Swatch_HR.jpg",
  "84_Boxington_Swatch_HR.jpg",
  "85_Kitchen Green_Swatch_HR.jpg",
  "86_Garden_Swatch_HR.jpg",
  "87_Acorn_Swatch_HR.jpg",
  "88_Dark Brunswick Green_Swatch_HR.jpg",
  "91_Pea Green_Swatch_HR.jpg",
  "92_Green Verditer_Swatch_HR.jpg",
  "94_Canton_Swatch_HR.jpg",
  "95_Marine Blue_Swatch_HR.jpg",
  "96_Mid Azure Green_Swatch_HR.jpg",
  "99_Salix_Swatch_HR.jpg",
  "100_Pearl Colour_Swatch_HR.jpg",
  "101_Celestial Blue_Swatch_HR.jpg",
  "103_Sky Blue_Swatch_HR.jpg",
  "104_Blue Verditer_Swatch_HR.jpg",
  "105_Slaked Lime_Swatch_HR.jpg",
  "106_Gauze_Swatch_HR.jpg",
  "107_Bone China Blue_Swatch_HR.jpg",
  "108_James_Swatch_HR.jpg",
  "112_Mambo_Swatch_HR.jpg",
  "113_French Grey_Swatch_HR.jpg",
  "114_Mid Lead Colour_Swatch_HR.jpg",
  "115_Juniper Ash_Swatch_HR.jpg",
  "116_Thai Sapphire_Swatch_HR.jpg",
  "117_Lead Colour_Swatch_HR.jpg",
  "118_Dark Lead Colour_Swatch_HR.jpg",
  "119_Jack Black_Swatch_HR.jpg",
  "122_Middle Buff_Swatch_HR.jpg",
  "123_Light Bronze Green_Swatch_HR.jpg",
  "124_Chocolate Colour_Swatch_HR.jpg",
  "129_Shirting_Swatch_HR.jpg",
  "130_Joanna_Swatch_HR.jpg",
  "135_Sunlight_Swatch_HR.jpg",
  "137_Apple_Swatch_HR.jpg",
  "138_Aquamarine_Swatch_HR.jpg",
  "139_Chemise_Swatch_HR.jpg",
  "140_Tuscan Red_Swatch_HR.jpg",
  "142_Mushroom_Swatch_HR.jpg",
  "143_Rolling Fog_Swatch_HR.jpg",
  "144_Attic II_Swatch_HR.jpg",
  "148_Carys_Swatch_HR.jpg",
  "149_Slaked Lime - Mid_Swatch_HR.jpg",
  "150_Slaked Lime - Deep_Swatch_HR.jpg",
  "151_Slaked Lime - Dark_Swatch_HR.jpg",
  "152_Clay - Pale_Swatch_HR.jpg",
  "153_Clay - Mid_Swatch_HR.jpg",
  "155_Portland Stone - Pale_Swatch_HR.jpg",
  "157_Portland Stone - Dark_Swatch_HR.jpg",
  "158_Rolling Fog - Pale_Swatch_HR.jpg",
  "160_Rolling Fog - Dark_Swatch_HR.jpg",
  "161_French Grey - Pale_Swatch_HR.jpg",
  "162_French Grey - Mid_Swatch_HR.jpg",
  "163_French Grey - Dark_Swatch_HR.jpg",
  "164_Gauze - Mid_Swatch_HR.jpg",
  "165_Gauze - Deep_Swatch_HR.jpg",
  "166_Gauze - Dark_Swatch_HR.jpg",
  "167_Pearl Colour - Pale_Swatch_HR.jpg",
  "168_Pearl Colour - Mid_Swatch_HR.jpg",
  "169_Pearl Colour - Dark_Swatch_HR.jpg",
  "176_China Clay - Mid_Swatch_HR.jpg",
  "177_China Clay - Deep_Swatch_HR.jpg",
  "178_China Clay - Dark_Swatch_HR.jpg",
  "182_Bone China Blue - Pale_Swatch_HR.jpg",
  "183_Bone China Blue - Mid_Swatch_HR.jpg",
  "184_Bone China Blue - Deep_Swatch_HR.jpg",
  "189_Carmine_Swatch_HR.jpg",
  "190_Atomic Red_Swatch_HR.jpg",
  "191_Leather_Swatch_HR.jpg",
  "192_Theatre Red_Swatch_HR.jpg",
  "196_Trumpet_Swatch_HR.jpg",
  "198_Aquamarine Deep_Swatch_HR.jpg",
  "199_Phthalo Green_Swatch_HR.jpg",
  "203_Brighton_Swatch_HR.jpg",
  "206_Tivoli_Swatch_HR.jpg",
  "207_Deep Space Blue_Swatch_HR.jpg",
  "208_Hicks Blue_Swatch_HR.jpg",
  "209_Marigold_Swatch_HR.jpg",
  "213_Dorchester Pink_Swatch_HR.jpg",
  "216_Obsidian Green_Swatch_HR.jpg",
  "219_Mirror_Swatch_HR.jpg",
  "220_Pink Slip_Swatch_HR.jpg",
  "221_Basalt_Swatch_HR.jpg",
  "222_Loft White_Swatch_HR.jpg",
  "223_Shallows_Swatch_HR.jpg",
  "224_Inox_Swatch_HR.jpg",
  "225_Urbane Grey_Swatch_HR.jpg",
  "227_Scree_Swatch_HR.jpg",
  "228_Lamp Black_Swatch_HR.jpg",
  "229_Wood Ash_Swatch_HR.jpg",
  "230_Ceviche_Swatch_HR.jpg",
  "231_Fescue_Swatch_HR.jpg",
  "232_Cool Arbour_Swatch_HR.jpg",
  "233_Serpentine_Swatch_HR.jpg",
  "236_Flint_Swatch_HR.jpg",
  "242_Down_Swatch_HR.jpg",
  "243_Rubine Ashes_Swatch_HR.jpg",
  "244_Dash of Soot_Swatch_HR.jpg",
  "245_Perennial Grey_Swatch_HR.jpg",
  "248_Delicate Blue_Swatch_HR.jpg",
  "249_Pale Wedgwood_Swatch_HR.jpg",
  "250_Arquerite_Swatch_HR.jpg",
  "251_Woad_Swatch_HR.jpg",
  "252_Dock Blue_Swatch_HR.jpg",
  "255_Smalt_Swatch_HR.jpg",
  "256_Mazarine_Swatch_HR.jpg",
  "257_Royal Navy_Swatch_HR.jpg",
  "260_Air Force Blue_Swatch_HR.jpg",
  "263_Livid_Swatch_HR.jpg",
  "267_Blush_Swatch_HR.jpg",
  "268_Green_Stone_Pale_Swatch_HR.jpg",
  "269_Green_Stone_Light_Swatch_HR.jpg",
  "270_Green_Stone_Swatch_HR.jpg",
  "271_Rolling_Fog_Light_Swatch_HR.jpg",
  "272_Travertine_Light_Swatch_HR.jpg",
  "273_Travertine_Mid_Swatch_HR.jpg",
  "274_Confetti_Swatch_HR.jpg",
  "275_Hellebore_Swatch_HR.jpg",
  "276_Grey Stone_Swatch_HR.jpg",
  "277_Cordoba_Swatch_HR.jpg",
  "278_Pale Lupin_Swatch_HR.jpg",
  "280_Pleat_Swatch_HR.jpg",
  "281_Portland Stone - Light_Swatch_HR.jpg",
  "282_Aquamarine - Pale_Swatch_HR.jpg",
  "283_Aquamarine - Light_Swatch_HR.jpg",
  "284_Aquamarine - Mid_Swatch_HR.jpg",
  "293_Pompeian Grey_Swatch_HR.jpg",
  "295_Boringdon Green_Swatch_HR.jpg",
  "296_Windmill Lane_Swatch_HR.jpg",
  "297_Hopper_Swatch_HR.jpg",
  "298_Puck_Swatch_HR.jpg",
  "303_Jewel Beetle_Swatch_HR.jpg",
  "304_Ambleside_Swatch_HR_Swatch_HR.jpg",
  "306_Three Farm Green_Swatch_HR.jpg",
  "307_Hidey Hole_Swatch_HR.jpg",
  "310_Tea with Florence_Swatch_HR.jpg",
  "311_Goblin_Swatch_HR.jpg",
  "312_Harley Green_Swatch_HR.jpg",
  "313_Ferdinand_Swatch_HR.jpg",
  "314_Castell Pink_Swatch_HR.jpg",
  "315_Nether Red_Swatch_HR.jpg",
  "316_Arras_Swatch_HR.jpg",
  "317_Lute_Swatch_HR.jpg",
  "318_Scullery_Swatch_HR.jpg",
  "319_Travertine_Swatch_HR.jpg",
  "320_Elysian Ground_Swatch_HR.jpg",
  "321_Baluster_Swatch_HR.jpg",
  "322_Book Room Green_Swatch_HR.jpg",
  "323_Light Beauvais_Swatch_HR.jpg",
  "324_Vulcan_Swatch_HR.jpg",
  "325_Bone China Blue - Faint_Swatch_HR.jpg",
  "326_Etruria_Swatch_HR.jpg",
  "327_Obscura_Swatch_HR.jpg",
  "328_Silent_White_Pale_Swatch_HR.jpg",
  "329_Silent_White_Swatch_HR.jpg",
  "330_Silent_White_Mid_Swatch_HR.jpg",
  "331_Silent_White_Deep_Swatch_HR.jpg",
  "332_Masquerade_Light_Swatch_HR.jpg",
  "333_Masquerade_Mid_Swatch_HR.jpg",
  "334_Masquerade_Swatch_HR.jpg",
  "335_Indian_Yellow_Swatch_HR.jpg",
  "336_Bassoon_Swatch_HR.jpg",
  "337_Giallo_Swatch_HR.jpg",
  "338_Madeleine_Swatch_HR.jpg",
  "339_Bombolone_Swatch_HR.jpg",
  "340_Galette_Swatch_HR.jpg",
  "341_Split Pink_Swatch_HR.jpg",
  "342_Affogato_Swatch_HR.jpg",
  "343_Muscovado_Swatch_HR.jpg",
  "344_Mochi_Swatch_HR.jpg",
  "345_Ganache_Swatch_HR.jpg",
];

function parseColorFromFilename(filename: string): Color | null {
  const match = filename.match(/^(\d+)_(.+?)(?:_Swatch_HR)*_Swatch_HR\.jpg$/);
  if (!match) {
    const simpleMatch = filename.match(/^(\d+)_(.+)_Swatch_HR\.jpg$/);
    if (!simpleMatch) return null;
    const [, idStr, rawName] = simpleMatch;
    const name = rawName.replace(/_/g, ' ').replace(/-/g, ' - ').trim();
    return {
      id: parseInt(idStr, 10),
      name,
      filename,
      brand: 'Little Greene'
    };
  }
  const [, idStr, rawName] = match;
  const name = rawName.replace(/_/g, ' ').replace(/-/g, ' - ').trim();
  return {
    id: parseInt(idStr, 10),
    name,
    filename,
    brand: 'Little Greene'
  };
}

const littleGreeneColors: Color[] = colorFilenames
  .map(parseColorFromFilename)
  .filter((c): c is Color => c !== null)
  .sort((a, b) => a.id - b.id);

// LOGGIA decorative finishes — 84-colour palette (GOCCE COLORATE).
// Swatches render from `hex`; `scene` is an optional painted-room photo.
const loggiaColors: Color[] = [
  { id: 1, name: "Almond Chip", brand: "LOGGIA", hex: "#d6c5b0", scene: "/images/loggia/scenes/almond-chip.jpg" },
  { id: 2, name: "Autumn White", brand: "LOGGIA", hex: "#ffe3ce", scene: "/images/loggia/scenes/autumn-white.jpg" },
  { id: 3, name: "Background Beige", brand: "LOGGIA", hex: "#d0bb9b", scene: "/images/loggia/scenes/background-beige.jpg" },
  { id: 4, name: "Blue Country", brand: "LOGGIA", hex: "#7695aa", scene: "/images/loggia/scenes/blue-country.jpg" },
  { id: 5, name: "Blue Trace", brand: "LOGGIA", hex: "#d3eff1", scene: "/images/loggia/scenes/blue-trace.jpg" },
  { id: 6, name: "Blue Vision", brand: "LOGGIA", hex: "#c7e2e4", scene: "/images/loggia/scenes/blue-vision.jpg" },
  { id: 7, name: "Bradford Beige", brand: "LOGGIA", hex: "#d3aba0", scene: "/images/loggia/scenes/bradford-beige.jpg" },
  { id: 8, name: "Bradford Brown", brand: "LOGGIA", hex: "#41353b", scene: "/images/loggia/scenes/bradford-brown.jpg" },
  { id: 9, name: "Chaff", brand: "LOGGIA", hex: "#e2c4a2", scene: "/images/loggia/scenes/chaff.jpg" },
  { id: 10, name: "Chateau Rose", brand: "LOGGIA", hex: "#ab6e6d", scene: "/images/loggia/scenes/chateau-rose.jpg" },
  { id: 11, name: "Chinchilla", brand: "LOGGIA", hex: "#b2a9a9", scene: "/images/loggia/scenes/chinchilla.jpg" },
  { id: 12, name: "Cloud Mist", brand: "LOGGIA", hex: "#b7b3b4", scene: "/images/loggia/scenes/cloud-mist.jpg" },
  { id: 13, name: "Coachlight", brand: "LOGGIA", hex: "#f0c083", scene: undefined },
  { id: 14, name: "Cotillion Red", brand: "LOGGIA", hex: "#883030", scene: "/images/loggia/scenes/cotillion-red.jpg" },
  { id: 15, name: "Cozy Corner", brand: "LOGGIA", hex: "#7aa8c0", scene: "/images/loggia/scenes/cozy-corner.jpg" },
  { id: 16, name: "Creamy White", brand: "LOGGIA", hex: "#fff5dd", scene: "/images/loggia/scenes/creamy-white.jpg" },
  { id: 17, name: "Crete Barrel", brand: "LOGGIA", hex: "#7c715b", scene: "/images/loggia/scenes/crete-barrel.jpg" },
  { id: 18, name: "Desert View", brand: "LOGGIA", hex: "#e0bfac", scene: "/images/loggia/scenes/desert-view.jpg" },
  { id: 19, name: "Drifting Cloud", brand: "LOGGIA", hex: "#e9dcd4", scene: "/images/loggia/scenes/drifting-cloud.jpg" },
  { id: 20, name: "Evening Pool", brand: "LOGGIA", hex: "#004447", scene: "/images/loggia/scenes/evening-pool.jpg" },
  { id: 21, name: "Fresh Biscuit", brand: "LOGGIA", hex: "#dfb991", scene: "/images/loggia/scenes/fresh-biscuit.jpg" },
  { id: 22, name: "Garden Dust", brand: "LOGGIA", hex: "#aa9591", scene: "/images/loggia/scenes/garden-dust.jpg" },
  { id: 23, name: "Gazebo", brand: "LOGGIA", hex: "#9a9071", scene: "/images/loggia/scenes/gazebo.jpg" },
  { id: 24, name: "Gray Foam", brand: "LOGGIA", hex: "#d7d4ce", scene: "/images/loggia/scenes/gray-foam.jpg" },
  { id: 25, name: "Gray Night", brand: "LOGGIA", hex: "#4b555f", scene: "/images/loggia/scenes/gray-night.jpg" },
  { id: 26, name: "Heart Of Palm", brand: "LOGGIA", hex: "#beb99e", scene: "/images/loggia/scenes/heart-of-palm.jpg" },
  { id: 27, name: "Hint Of Blue", brand: "LOGGIA", hex: "#b2d4d5", scene: "/images/loggia/scenes/hint-of-blue.jpg" },
  { id: 28, name: "Hubbard Squash", brand: "LOGGIA", hex: "#b0734b", scene: "/images/loggia/scenes/hubbard-squash.jpg" },
  { id: 29, name: "Ivory Porcelain", brand: "LOGGIA", hex: "#e3d4b5", scene: "/images/loggia/scenes/ivory-porcelain.jpg" },
  { id: 30, name: "Ivory Yellow", brand: "LOGGIA", hex: "#fff2cb", scene: "/images/loggia/scenes/ivory-yellow.jpg" },
  { id: 31, name: "Liberty Grey", brand: "LOGGIA", hex: "#646b7a", scene: "/images/loggia/scenes/liberty-grey.jpg" },
  { id: 32, name: "Light Approach", brand: "LOGGIA", hex: "#e3dbc9", scene: "/images/loggia/scenes/light-approach.jpg" },
  { id: 33, name: "Little Angel", brand: "LOGGIA", hex: "#eee5cb", scene: "/images/loggia/scenes/little-angel.jpg" },
  { id: 34, name: "Little Little", brand: "LOGGIA", hex: "#b1c3a5", scene: "/images/loggia/scenes/little-little.jpg" },
  { id: 35, name: "Manila", brand: "LOGGIA", hex: "#8f7a62", scene: "/images/loggia/scenes/manila.jpg" },
  { id: 36, name: "Mature Gray", brand: "LOGGIA", hex: "#d0cdc9", scene: "/images/loggia/scenes/mature-gray.jpg" },
  { id: 37, name: "Mauve Bisque", brand: "LOGGIA", hex: "#e1cbbc", scene: "/images/loggia/scenes/mauve-bisque.jpg" },
  { id: 38, name: "Misty Shadow", brand: "LOGGIA", hex: "#b3a58c", scene: "/images/loggia/scenes/misty-shadow.jpg" },
  { id: 39, name: "Mobe Pearl", brand: "LOGGIA", hex: "#f0e0d4", scene: "/images/loggia/scenes/mobe-pearl.jpg" },
  { id: 40, name: "Morning Moss", brand: "LOGGIA", hex: "#645d41", scene: "/images/loggia/scenes/morning-moss.jpg" },
  { id: 41, name: "Musing", brand: "LOGGIA", hex: "#ffd3a8", scene: "/images/loggia/scenes/musing.jpg" },
  { id: 42, name: "Orchid Scent", brand: "LOGGIA", hex: "#c9bec6", scene: "/images/loggia/scenes/orchid-scent.jpg" },
  { id: 43, name: "Outpost Gray", brand: "LOGGIA", hex: "#62565e", scene: "/images/loggia/scenes/outpost-gray.jpg" },
  { id: 44, name: "Peach Pinch", brand: "LOGGIA", hex: "#f6e9d0", scene: undefined },
  { id: 45, name: "Perfect Plum", brand: "LOGGIA", hex: "#3a2c3a", scene: "/images/loggia/scenes/perfect-plum.jpg" },
  { id: 46, name: "Pioneer Red", brand: "LOGGIA", hex: "#843f43", scene: "/images/loggia/scenes/pioneer-red.jpg" },
  { id: 47, name: "Platinum", brand: "LOGGIA", hex: "#969391", scene: "/images/loggia/scenes/platinum.jpg" },
  { id: 48, name: "Pueblo Peach", brand: "LOGGIA", hex: "#fbc2b5", scene: "/images/loggia/scenes/pueblo-peach.jpg" },
  { id: 49, name: "Quilter's Threads", brand: "LOGGIA", hex: "#cbc1b8", scene: "/images/loggia/scenes/quilter-s-threads.jpg" },
  { id: 50, name: "Ripe Wheat", brand: "LOGGIA", hex: "#e5c18a", scene: "/images/loggia/scenes/ripe-wheat.jpg" },
  { id: 51, name: "Robust Vine", brand: "LOGGIA", hex: "#19372c", scene: "/images/loggia/scenes/robust-vine.jpg" },
  { id: 52, name: "Rosy Dawn", brand: "LOGGIA", hex: "#e6d8d0", scene: "/images/loggia/scenes/rosy-dawn.jpg" },
  { id: 53, name: "Rye", brand: "LOGGIA", hex: "#c59f75", scene: "/images/loggia/scenes/rye.jpg" },
  { id: 54, name: "Saddle Brown", brand: "LOGGIA", hex: "#3d312a", scene: "/images/loggia/scenes/saddle-brown.jpg" },
  { id: 55, name: "Saddle Sheen", brand: "LOGGIA", hex: "#866745", scene: "/images/loggia/scenes/saddle-sheen.jpg" },
  { id: 56, name: "Sea Nymph Green", brand: "LOGGIA", hex: "#a5ddde", scene: undefined },
  { id: 57, name: "Silent Bliss", brand: "LOGGIA", hex: "#f4d7b9", scene: "/images/loggia/scenes/silent-bliss.jpg" },
  { id: 58, name: "Silver Coin", brand: "LOGGIA", hex: "#cbc7c1", scene: "/images/loggia/scenes/silver-coin.jpg" },
  { id: 59, name: "Silver Skates", brand: "LOGGIA", hex: "#a8b6bd", scene: "/images/loggia/scenes/silver-skates.jpg" },
  { id: 60, name: "Smokey Taupe", brand: "LOGGIA", hex: "#af9590", scene: "/images/loggia/scenes/smokey-taupe.jpg" },
  { id: 61, name: "Spoonbread", brand: "LOGGIA", hex: "#ffdeb8", scene: "/images/loggia/scenes/spoonbread.jpg" },
  { id: 62, name: "Spring Kissed", brand: "LOGGIA", hex: "#ccd0a2", scene: "/images/loggia/scenes/spring-kissed.jpg" },
  { id: 63, name: "Stairstep", brand: "LOGGIA", hex: "#907a6a", scene: "/images/loggia/scenes/stairstep.jpg" },
  { id: 64, name: "Stone Fence", brand: "LOGGIA", hex: "#313c46", scene: "/images/loggia/scenes/stone-fence.jpg" },
  { id: 65, name: "Stormy Sky", brand: "LOGGIA", hex: "#605b57", scene: "/images/loggia/scenes/stormy-sky.jpg" },
  { id: 66, name: "Stucco Beige", brand: "LOGGIA", hex: "#ab9b89", scene: "/images/loggia/scenes/stucco-beige.jpg" },
  { id: 67, name: "Swan Wing", brand: "LOGGIA", hex: "#f9f0de", scene: "/images/loggia/scenes/swan-wing.jpg" },
  { id: 68, name: "Tempest Brown", brand: "LOGGIA", hex: "#473237", scene: "/images/loggia/scenes/tempest-brown.jpg" },
  { id: 69, name: "Tigerstripe", brand: "LOGGIA", hex: "#a05b3e", scene: "/images/loggia/scenes/tigerstripe.jpg" },
  { id: 70, name: "Turned Earth", brand: "LOGGIA", hex: "#36353d", scene: "/images/loggia/scenes/turned-earth.jpg" },
  { id: 71, name: "Versatile Neutral", brand: "LOGGIA", hex: "#d5cbb1", scene: "/images/loggia/scenes/versatile-neutral.jpg" },
  { id: 72, name: "Victorian Gray", brand: "LOGGIA", hex: "#afaaa6", scene: "/images/loggia/scenes/victorian-gray.jpg" },
  { id: 73, name: "Violet Whisper", brand: "LOGGIA", hex: "#e7e9e4", scene: "/images/loggia/scenes/violet-whisper.jpg" },
  { id: 74, name: "Vulcan Blue", brand: "LOGGIA", hex: "#2a3c4b", scene: "/images/loggia/scenes/vulcan-blue.jpg" },
  { id: 75, name: "Walden White", brand: "LOGGIA", hex: "#dfd8ca", scene: "/images/loggia/scenes/walden-white.jpg" },
  { id: 76, name: "Weak Tea", brand: "LOGGIA", hex: "#f8c2a6", scene: "/images/loggia/scenes/weak-tea.jpg" },
  { id: 77, name: "Weatherbelt", brand: "LOGGIA", hex: "#79858b", scene: "/images/loggia/scenes/weatherbelt.jpg" },
  { id: 78, name: "Wesley Blue", brand: "LOGGIA", hex: "#446477", scene: "/images/loggia/scenes/wesley-blue.jpg" },
  { id: 79, name: "White Castle", brand: "LOGGIA", hex: "#cecac4", scene: "/images/loggia/scenes/white-castle.jpg" },
  { id: 80, name: "White Lace", brand: "LOGGIA", hex: "#f1ebde", scene: "/images/loggia/scenes/white-lace.jpg" },
  { id: 81, name: "White Whale", brand: "LOGGIA", hex: "#afb4b6", scene: "/images/loggia/scenes/white-whale.jpg" },
  { id: 82, name: "White Wing", brand: "LOGGIA", hex: "#ded6d1", scene: "/images/loggia/scenes/white-wing.jpg" },
  { id: 83, name: "Wintersweet Berry", brand: "LOGGIA", hex: "#ba7369", scene: "/images/loggia/scenes/wintersweet-berry.jpg" },
  { id: 84, name: "Wise Sage", brand: "LOGGIA", hex: "#c0b69c", scene: "/images/loggia/scenes/wise-sage.jpg" },
];

export const colors: Color[] = [...littleGreeneColors, ...loggiaColors];

export const brands = ['Little Greene', 'LOGGIA'] as const;

export type Brand = typeof brands[number];

export function getColorsByBrand(brand: Brand): Color[] {
  return colors.filter(c => c.brand === brand);
}

export function searchColors(query: string): Color[] {
  const lowerQuery = query.toLowerCase();
  return colors.filter(c => 
    c.name.toLowerCase().includes(lowerQuery) ||
    c.id.toString().includes(lowerQuery)
  );
}

