export type Color = {
  id: number;
  name: string;
  filename: string;
  brand: string;
};

const colorFilenames = [
  "1_China Clay_Swatch_HR.jpg",
  "3_Light Peachblossom_Swatch_HR.jpg",
  "6_Ashes of Roses_Swatch_HR.jpg",
  "7_Adventurer_Swatch_HR.jpg",
  "8_Purple Brown_Swatch_HR.jpg",
  "13_Mischief_Swatch_HR.jpg",
  "14_Baked Cherry_Swatch_HR.jpg",
  "15_Bronze Red_Swatch_HR.jpg",
  "21_Orange Aurora_Swatch_HR.jpg",
  "24_Heat_Swatch_HR.jpg",
  "25_Hollyhock_Swatch_HR.jpg",
  "26_Julies Dream_Swatch_HR.jpg",
  "29_Beauvais Lilac_Swatch_HR.jpg",
  "31_Roman Plaster_Swatch_HR.jpg",
  "33_Linen Wash_Swatch_HR.jpg",
  "34_Stone-Pale-Warm_Swatch_HR.jpg",
  "37_Stock_Swatch_HR.jpg",
  "38_Hammock_Swatch_HR.jpg",
  "39_Clay_Swatch_HR.jpg",
  "40_Silt_Swatch_HR.jpg",
  "41_Whitening_Swatch_HR.jpg",
  "46_Yellow-Pink_Swatch_HR.jpg",
  "47_Mister David_Swatch_HR.jpg",
  "49_First Light_Swatch_HR.jpg",
  "53_Light Gold_Swatch_HR.jpg",
  "56_Invisible Green_Swatch_HR.jpg",
  "63_Oak Apple_Swatch_HR.jpg",
  "64_Bath Stone_Swatch_HR.jpg",
  "70_Pale Lime_Swatch_HR.jpg",
  "71_Citrine_Swatch_HR.jpg",
  "72_Olive Colour_Swatch_HR.jpg",
  "74_White Lead_Swatch_HR.jpg",
  "77_Portland Stone_Swatch_HR.jpg",
  "78_Tracery II_Swatch_HR.jpg",
  "79_Normandy Grey_Swatch_HR.jpg",
  "80_Sage Green_Swatch_HR.jpg",
  "84_Boxington_Swatch_HR.jpg",
  "85_Kitchen Green_Swatch_HR.jpg",
  "86_Garden_Swatch_HR.jpg",
  "87_Acorn_Swatch_HR.jpg",
  "88_Dark Brunswick Green_Swatch_HR.jpg",
  "91_Pea Green_Swatch_HR.jpg",
  "92_Green Verditer_Swatch_HR.jpg",
  "94_Canton_Swatch_HR.jpg",
  "95_Marine Blue_Swatch_HR.jpg",
  "96_Mid Azure Green_Swatch_HR.jpg",
  "99_Salix_Swatch_HR.jpg",
  "100_Pearl Colour_Swatch_HR.jpg",
  "101_Celestial Blue_Swatch_HR.jpg",
  "103_Sky Blue_Swatch_HR.jpg",
  "104_Blue Verditer_Swatch_HR.jpg",
  "105_Slaked Lime_Swatch_HR.jpg",
  "106_Gauze_Swatch_HR.jpg",
  "107_Bone China Blue_Swatch_HR.jpg",
  "108_James_Swatch_HR.jpg",
  "112_Mambo_Swatch_HR.jpg",
  "113_French Grey_Swatch_HR.jpg",
  "114_Mid Lead Colour_Swatch_HR.jpg",
  "115_Juniper Ash_Swatch_HR.jpg",
  "116_Thai Sapphire_Swatch_HR.jpg",
  "117_Lead Colour_Swatch_HR.jpg",
  "118_Dark Lead Colour_Swatch_HR.jpg",
  "119_Jack Black_Swatch_HR.jpg",
  "122_Middle Buff_Swatch_HR.jpg",
  "123_Light Bronze Green_Swatch_HR.jpg",
  "124_Chocolate Colour_Swatch_HR.jpg",
  "129_Shirting_Swatch_HR.jpg",
  "130_Joanna_Swatch_HR.jpg",
  "135_Sunlight_Swatch_HR.jpg",
  "137_Apple_Swatch_HR.jpg",
  "138_Aquamarine_Swatch_HR.jpg",
  "139_Chemise_Swatch_HR.jpg",
  "140_Tuscan Red_Swatch_HR.jpg",
  "142_Mushroom_Swatch_HR.jpg",
  "143_Rolling Fog_Swatch_HR.jpg",
  "144_Attic II_Swatch_HR.jpg",
  "148_Carys_Swatch_HR.jpg",
  "149_Slaked Lime - Mid_Swatch_HR.jpg",
  "150_Slaked Lime - Deep_Swatch_HR.jpg",
  "151_Slaked Lime - Dark_Swatch_HR.jpg",
  "152_Clay - Pale_Swatch_HR.jpg",
  "153_Clay - Mid_Swatch_HR.jpg",
  "155_Portland Stone - Pale_Swatch_HR.jpg",
  "157_Portland Stone - Dark_Swatch_HR.jpg",
  "158_Rolling Fog - Pale_Swatch_HR.jpg",
  "160_Rolling Fog - Dark_Swatch_HR.jpg",
  "161_French Grey - Pale_Swatch_HR.jpg",
  "162_French Grey - Mid_Swatch_HR.jpg",
  "163_French Grey - Dark_Swatch_HR.jpg",
  "164_Gauze - Mid_Swatch_HR.jpg",
  "165_Gauze - Deep_Swatch_HR.jpg",
  "166_Gauze - Dark_Swatch_HR.jpg",
  "167_Pearl Colour - Pale_Swatch_HR.jpg",
  "168_Pearl Colour - Mid_Swatch_HR.jpg",
  "169_Pearl Colour - Dark_Swatch_HR.jpg",
  "176_China Clay - Mid_Swatch_HR.jpg",
  "177_China Clay - Deep_Swatch_HR.jpg",
  "178_China Clay - Dark_Swatch_HR.jpg",
  "182_Bone China Blue - Pale_Swatch_HR.jpg",
  "183_Bone China Blue - Mid_Swatch_HR.jpg",
  "184_Bone China Blue - Deep_Swatch_HR.jpg",
  "189_Carmine_Swatch_HR.jpg",
  "190_Atomic Red_Swatch_HR.jpg",
  "191_Leather_Swatch_HR.jpg",
  "192_Theatre Red_Swatch_HR.jpg",
  "196_Trumpet_Swatch_HR.jpg",
  "198_Aquamarine Deep_Swatch_HR.jpg",
  "199_Phthalo Green_Swatch_HR.jpg",
  "203_Brighton_Swatch_HR.jpg",
  "206_Tivoli_Swatch_HR.jpg",
  "207_Deep Space Blue_Swatch_HR.jpg",
  "208_Hicks Blue_Swatch_HR.jpg",
  "209_Marigold_Swatch_HR.jpg",
  "213_Dorchester Pink_Swatch_HR.jpg",
  "216_Obsidian Green_Swatch_HR.jpg",
  "219_Mirror_Swatch_HR.jpg",
  "220_Pink Slip_Swatch_HR.jpg",
  "221_Basalt_Swatch_HR.jpg",
  "222_Loft White_Swatch_HR.jpg",
  "223_Shallows_Swatch_HR.jpg",
  "224_Inox_Swatch_HR.jpg",
  "225_Urbane Grey_Swatch_HR.jpg",
  "227_Scree_Swatch_HR.jpg",
  "228_Lamp Black_Swatch_HR.jpg",
  "229_Wood Ash_Swatch_HR.jpg",
  "230_Ceviche_Swatch_HR.jpg",
  "231_Fescue_Swatch_HR.jpg",
  "232_Cool Arbour_Swatch_HR.jpg",
  "233_Serpentine_Swatch_HR.jpg",
  "236_Flint_Swatch_HR.jpg",
  "242_Down_Swatch_HR.jpg",
  "243_Rubine Ashes_Swatch_HR.jpg",
  "244_Dash of Soot_Swatch_HR.jpg",
  "245_Perennial Grey_Swatch_HR.jpg",
  "248_Delicate Blue_Swatch_HR.jpg",
  "249_Pale Wedgwood_Swatch_HR.jpg",
  "250_Arquerite_Swatch_HR.jpg",
  "251_Woad_Swatch_HR.jpg",
  "252_Dock Blue_Swatch_HR.jpg",
  "255_Smalt_Swatch_HR.jpg",
  "256_Mazarine_Swatch_HR.jpg",
  "257_Royal Navy_Swatch_HR.jpg",
  "260_Air Force Blue_Swatch_HR.jpg",
  "263_Livid_Swatch_HR.jpg",
  "267_Blush_Swatch_HR.jpg",
  "268_Green_Stone_Pale_Swatch_HR.jpg",
  "269_Green_Stone_Light_Swatch_HR.jpg",
  "270_Green_Stone_Swatch_HR.jpg",
  "271_Rolling_Fog_Light_Swatch_HR.jpg",
  "272_Travertine_Light_Swatch_HR.jpg",
  "273_Travertine_Mid_Swatch_HR.jpg",
  "274_Confetti_Swatch_HR.jpg",
  "275_Hellebore_Swatch_HR.jpg",
  "276_Grey Stone_Swatch_HR.jpg",
  "277_Cordoba_Swatch_HR.jpg",
  "278_Pale Lupin_Swatch_HR.jpg",
  "280_Pleat_Swatch_HR.jpg",
  "281_Portland Stone - Light_Swatch_HR.jpg",
  "282_Aquamarine - Pale_Swatch_HR.jpg",
  "283_Aquamarine - Light_Swatch_HR.jpg",
  "284_Aquamarine - Mid_Swatch_HR.jpg",
  "293_Pompeian Grey_Swatch_HR.jpg",
  "295_Boringdon Green_Swatch_HR.jpg",
  "296_Windmill Lane_Swatch_HR.jpg",
  "297_Hopper_Swatch_HR.jpg",
  "298_Puck_Swatch_HR.jpg",
  "303_Jewel Beetle_Swatch_HR.jpg",
  "304_Ambleside_Swatch_HR_Swatch_HR.jpg",
  "306_Three Farm Green_Swatch_HR.jpg",
  "307_Hidey Hole_Swatch_HR.jpg",
  "310_Tea with Florence_Swatch_HR.jpg",
  "311_Goblin_Swatch_HR.jpg",
  "312_Harley Green_Swatch_HR.jpg",
  "313_Ferdinand_Swatch_HR.jpg",
  "314_Castell Pink_Swatch_HR.jpg",
  "315_Nether Red_Swatch_HR.jpg",
  "316_Arras_Swatch_HR.jpg",
  "317_Lute_Swatch_HR.jpg",
  "318_Scullery_Swatch_HR.jpg",
  "319_Travertine_Swatch_HR.jpg",
  "320_Elysian Ground_Swatch_HR.jpg",
  "321_Baluster_Swatch_HR.jpg",
  "322_Book Room Green_Swatch_HR.jpg",
  "323_Light Beauvais_Swatch_HR.jpg",
  "324_Vulcan_Swatch_HR.jpg",
  "325_Bone China Blue - Faint_Swatch_HR.jpg",
  "326_Etruria_Swatch_HR.jpg",
  "327_Obscura_Swatch_HR.jpg",
  "328_Silent_White_Pale_Swatch_HR.jpg",
  "329_Silent_White_Swatch_HR.jpg",
  "330_Silent_White_Mid_Swatch_HR.jpg",
  "331_Silent_White_Deep_Swatch_HR.jpg",
  "332_Masquerade_Light_Swatch_HR.jpg",
  "333_Masquerade_Mid_Swatch_HR.jpg",
  "334_Masquerade_Swatch_HR.jpg",
  "335_Indian_Yellow_Swatch_HR.jpg",
  "336_Bassoon_Swatch_HR.jpg",
  "337_Giallo_Swatch_HR.jpg",
  "338_Madeleine_Swatch_HR.jpg",
  "339_Bombolone_Swatch_HR.jpg",
  "340_Galette_Swatch_HR.jpg",
  "341_Split Pink_Swatch_HR.jpg",
  "342_Affogato_Swatch_HR.jpg",
  "343_Muscovado_Swatch_HR.jpg",
  "344_Mochi_Swatch_HR.jpg",
  "345_Ganache_Swatch_HR.jpg",
];

function parseColorFromFilename(filename: string): Color | null {
  const match = filename.match(/^(\d+)_(.+?)(?:_Swatch_HR)*_Swatch_HR\.jpg$/);
  if (!match) {
    const simpleMatch = filename.match(/^(\d+)_(.+)_Swatch_HR\.jpg$/);
    if (!simpleMatch) return null;
    const [, idStr, rawName] = simpleMatch;
    const name = rawName.replace(/_/g, ' ').replace(/-/g, ' - ').trim();
    return {
      id: parseInt(idStr, 10),
      name,
      filename,
      brand: 'Little Greene'
    };
  }
  const [, idStr, rawName] = match;
  const name = rawName.replace(/_/g, ' ').replace(/-/g, ' - ').trim();
  return {
    id: parseInt(idStr, 10),
    name,
    filename,
    brand: 'Little Greene'
  };
}

export const colors: Color[] = colorFilenames
  .map(parseColorFromFilename)
  .filter((c): c is Color => c !== null)
  .sort((a, b) => a.id - b.id);

export const brands = ['Little Greene'] as const;

export type Brand = typeof brands[number];

export function getColorsByBrand(brand: Brand): Color[] {
  return colors.filter(c => c.brand === brand);
}

export function searchColors(query: string): Color[] {
  const lowerQuery = query.toLowerCase();
  return colors.filter(c => 
    c.name.toLowerCase().includes(lowerQuery) ||
    c.id.toString().includes(lowerQuery)
  );
}

