// AUTO-GENERATED from the Blue Dolphin asset folder. Edit names here if needed.
export type ToolProduct = {
  id: string;
  name: string;
  category: string;
  subcategory: string;
  image: string;
  gallery: string[];
  sizes?: string;
  video?: string;
};

export const toolProducts: ToolProduct[] = [
  { id: "ninja-brushes-ninja-330-50mm-flat", name: "Ninja 330 50mm Flat", category: "Brushes & Rollers", subcategory: "Brushes", image: "/images/tools/ninja-brushes/ninja-330-50mm-flat/1.png", gallery: ["/images/tools/ninja-brushes/ninja-330-50mm-flat/1.png"], video: "/videos/tools/ninja-brushes.mp4" },
  { id: "ninja-brushes-ninja-330-50mm-rattail", name: "Ninja 330 50mm Rattail", category: "Brushes & Rollers", subcategory: "Brushes", image: "/images/tools/ninja-brushes/ninja-330-50mm-rattail/1.png", gallery: ["/images/tools/ninja-brushes/ninja-330-50mm-rattail/1.png"], video: "/videos/tools/ninja-brushes.mp4" },
  { id: "series-330-holders-mini-frame", name: "Dolphin mini roller frame", category: "Brushes & Rollers", subcategory: "Holders", image: "/images/tools/series-330/holders-mini-frame/1.png", gallery: ["/images/tools/series-330/holders-mini-frame/1.png", "/images/tools/series-330/holders-mini-frame/2.jpg"], video: "/videos/tools/series-330-holders.mp4" },
  { id: "series-330-holders-aluminium-25", name: "Dolphin aluminium frame 25 cm", category: "Brushes & Rollers", subcategory: "Holders", image: "/images/tools/series-330/holders-aluminium-25/1.png", gallery: ["/images/tools/series-330/holders-aluminium-25/1.png", "/images/tools/series-330/holders-aluminium-25/2.jpg"], video: "/videos/tools/series-330-holders.mp4" },
  { id: "series-330-holders-swivel-frame", name: "330 swivel roller frame", category: "Brushes & Rollers", subcategory: "Holders", image: "/images/tools/series-330/holders-swivel-frame/1.jpg", gallery: ["/images/tools/series-330/holders-swivel-frame/1.jpg"], video: "/videos/tools/series-330-holders.mp4" },
  { id: "series-330-holders-y-frame", name: "Dolphin Y-Frame 330", category: "Brushes & Rollers", subcategory: "Holders", image: "/images/tools/series-330/holders-y-frame/1.png", gallery: ["/images/tools/series-330/holders-y-frame/1.png", "/images/tools/series-330/holders-y-frame/2.jpg"], video: "/videos/tools/series-330-holders.mp4" },
  { id: "series-330-holders-jumbo", name: "Jumbo roller frame", category: "Brushes & Rollers", subcategory: "Holders", image: "/images/tools/series-330/holders-jumbo/1.png", gallery: ["/images/tools/series-330/holders-jumbo/1.png"], video: "/videos/tools/series-330-holders.mp4" },
  { id: "series-330-accessories-extender", name: "DolphinXtender extension pole 180 cm", category: "Brushes & Rollers", subcategory: "Accessories", image: "/images/tools/series-330/accessories-extender/1.png", gallery: ["/images/tools/series-330/accessories-extender/1.png", "/images/tools/series-330/accessories-extender/2.jpg"], video: "/videos/tools/series-330-rollers.mp4" },
  { id: "series-330-accessories-paint-tray", name: "330 paint tray", category: "Brushes & Rollers", subcategory: "Accessories", image: "/images/tools/series-330/accessories-paint-tray/1.png", gallery: ["/images/tools/series-330/accessories-paint-tray/1.png", "/images/tools/series-330/accessories-paint-tray/2.jpg"], video: "/videos/tools/series-330-rollers.mp4" },
  { id: "series-330-killer", name: "Killer", category: "Brushes & Rollers", subcategory: "Rollers", sizes: "25 · 37 · 45 cm", image: "/images/tools/series-330/killer-25-w13/1.png", gallery: ["/images/tools/series-330/killer-25-w13/1.png", "/images/tools/series-330/killer-25-w13/2.jpg", "/images/tools/series-330/killer-25-w9/1.png", "/images/tools/series-330/killer-37-w13/1.png", "/images/tools/series-330/killer-37-w13/2.jpg", "/images/tools/series-330/killer-37-w9/1.png"], video: "/videos/tools/series-330-killer.mp4" },
  { id: "series-330-killer-yframe", name: "Killer (Y-Frame Set)", category: "Brushes & Rollers", subcategory: "Holders", sizes: "37 · 45 cm", image: "/images/tools/series-330/killer-37-w13-yframe/1.png", gallery: ["/images/tools/series-330/killer-37-w13-yframe/1.png", "/images/tools/series-330/killer-37-w13-yframe/2.jpg", "/images/tools/series-330/killer-37-w9-yframe/1.png", "/images/tools/series-330/killer-45-w13-yframe/1.png", "/images/tools/series-330/killer-45-w13-yframe/2.jpg", "/images/tools/series-330/killer-45-w9-yframe/1.png"], video: "/videos/tools/series-330-killer.mp4" },
  { id: "series-330-spinner", name: "Spinner", category: "Brushes & Rollers", subcategory: "Rollers", sizes: "25 · 37 cm", image: "/images/tools/series-330/spinner-25-w13/1.png", gallery: ["/images/tools/series-330/spinner-25-w13/1.png", "/images/tools/series-330/spinner-25-w13/2.jpg", "/images/tools/series-330/spinner-25-w9/1.png", "/images/tools/series-330/spinner-37-w13/1.png", "/images/tools/series-330/spinner-37-w13/2.jpg", "/images/tools/series-330/spinner-37-w9/1.png"], video: "/videos/tools/series-330-rollers.mp4" },
  { id: "series-330-spinner-yframe", name: "Spinner (Y-Frame Set)", category: "Brushes & Rollers", subcategory: "Holders", sizes: "37 · 45 cm", image: "/images/tools/series-330/spinner-37-w13-yframe/1.png", gallery: ["/images/tools/series-330/spinner-37-w13-yframe/1.png", "/images/tools/series-330/spinner-37-w13-yframe/2.jpg", "/images/tools/series-330/spinner-37-w9-yframe/1.png", "/images/tools/series-330/spinner-45-w13-yframe/1.png", "/images/tools/series-330/spinner-45-w9-yframe/1.png"], video: "/videos/tools/series-330-rollers.mp4" },
  { id: "tapes-painters-tape-25mm", name: "Painter’s Tape — 25 mm × 50 m", category: "Tapes", subcategory: "", image: "/images/tools/tapes/painters-tape-25mm/1.png", gallery: ["/images/tools/tapes/painters-tape-25mm/1.png", "/images/tools/tapes/painters-tape-25mm/2.jpg"] },
  { id: "tapes-painters-tape-30mm", name: "Painter’s Tape — 30 mm × 50 m", category: "Tapes", subcategory: "", image: "/images/tools/tapes/painters-tape-30mm/1.png", gallery: ["/images/tools/tapes/painters-tape-30mm/1.png", "/images/tools/tapes/painters-tape-30mm/2.jpg"] },
  { id: "tapes-painters-tape-38mm", name: "Painter’s Tape — 38 mm × 50 m", category: "Tapes", subcategory: "", image: "/images/tools/tapes/painters-tape-38mm/1.png", gallery: ["/images/tools/tapes/painters-tape-38mm/1.png", "/images/tools/tapes/painters-tape-38mm/2.jpg"] },
  { id: "tapes-painters-tape-48mm", name: "Painter’s Tape — 48 mm × 50 m", category: "Tapes", subcategory: "", image: "/images/tools/tapes/painters-tape-48mm/1.png", gallery: ["/images/tools/tapes/painters-tape-48mm/1.png", "/images/tools/tapes/painters-tape-48mm/2.png", "/images/tools/tapes/painters-tape-48mm/3.jpg", "/images/tools/tapes/painters-tape-48mm/4.jpg"] },
  { id: "abrasive-articles-abrasive-sponge-100-x-68-x-25-mm", name: "Abrasive sponge 100 x 68 x 25 mm", category: "Abrasive Articles", subcategory: "", image: "/images/tools/abrasive-articles/abrasive-sponge-100-x-68-x-25-mm/1.png", gallery: ["/images/tools/abrasive-articles/abrasive-sponge-100-x-68-x-25-mm/1.png"] },
  { id: "abrasive-articles-abrasive-sponge-cut", name: "Abrasive sponge cut", category: "Abrasive Articles", subcategory: "", image: "/images/tools/abrasive-articles/abrasive-sponge-cut/1.png", gallery: ["/images/tools/abrasive-articles/abrasive-sponge-cut/1.png"] },
  { id: "abrasive-articles-ergonomic-kit", name: "Ergonomic Hand-Sanding Kit", category: "Abrasive Articles", subcategory: "", image: "/images/tools/abrasive-articles/ergonomic-kit/1.png", gallery: ["/images/tools/abrasive-articles/ergonomic-kit/1.png"] },
  { id: "abrasive-articles-ergonomic-refill", name: "Ergonomic Hand-Sanding Refill Pack", category: "Abrasive Articles", subcategory: "", image: "/images/tools/abrasive-articles/ergonomic-refill/1.png", gallery: ["/images/tools/abrasive-articles/ergonomic-refill/1.png", "/images/tools/abrasive-articles/ergonomic-refill/2.jpg"] },
  { id: "abrasive-articles-hand-kit", name: "Hand-Sanding Kit", category: "Abrasive Articles", subcategory: "", image: "/images/tools/abrasive-articles/hand-kit/1.png", gallery: ["/images/tools/abrasive-articles/hand-kit/1.png"] },
  { id: "abrasive-articles-hand-refill", name: "Hand-Sanding Refill Pack", category: "Abrasive Articles", subcategory: "", image: "/images/tools/abrasive-articles/hand-refill/1.png", gallery: ["/images/tools/abrasive-articles/hand-refill/1.png", "/images/tools/abrasive-articles/hand-refill/2.jpg"] },
  { id: "abrasive-articles-palm-kit", name: "Palm-Sanding Kit", category: "Abrasive Articles", subcategory: "", image: "/images/tools/abrasive-articles/palm-kit/1.png", gallery: ["/images/tools/abrasive-articles/palm-kit/1.png"] },
  { id: "abrasive-articles-palm-refill", name: "Palm-Sanding Refill Pack", category: "Abrasive Articles", subcategory: "", image: "/images/tools/abrasive-articles/palm-refill/1.png", gallery: ["/images/tools/abrasive-articles/palm-refill/1.png", "/images/tools/abrasive-articles/palm-refill/2.jpg"] },
];

export type ToolCategory = { name: string; subcategories: string[] };
export const toolCategories: ToolCategory[] = [
  { name: "Brushes & Rollers", subcategories: ["Brushes", "Rollers", "Holders", "Accessories"] },
  { name: "Abrasive Articles", subcategories: [] },
  { name: "Tapes", subcategories: [] },
];
